openapi: 3.0.0
info:
  title: TODO API
  description: API documentation for the TODO app
  version: 1.0.0

paths:
  /todos:
    get:
      summary: Get all TODOs
      responses:
        '200':
          description: A list of TODO items
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      example: 1
                    task:
                      type: string
                      example: Learn Angular
                    completed:
                      type: boolean
                      example: false
    post:
      summary: Add a new TODO
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: integer
                task:
                  type: string
                completed:
                  type: boolean
      responses:
        '201':
          description: The created TODO item
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  task:
                    type: string
                  completed:
                    type: boolean
  /todos/{id}:
    delete:
      summary: Delete a TODO
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: TODO item deleted
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '404':
          description: TODO not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
